### ISSUE TITLE
Develop Disciplines view

### ISSUE THREAD

**Issue by m4rc1o** [Filipe-Rodrigues/SIGAA-De-Araque#48]

**Comment by Tarik-INC** [comment]
@AleGrillo 
@m4rc1o 
Views not implemented:

- ~Login and register~ #35 
- ~Home~ #21, #31 
- ~Projects~ # 30, #34
-  Researchers #49
-  Disciplines (under development )#48
- Research group #50
- ~Publications~ #46, #47 
- ~Profile~ #36, #38
